# Generated by Django 4.0.6 on 2023-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=50)),
                ('drugpicture', models.ImageField(null=True, upload_to='')),
                ('description1', models.TextField(max_length=70)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('OilPhoto', models.ImageField(upload_to='image_uploaded')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description1', models.CharField(blank=True, max_length=150)),
                ('description2', models.CharField(default='', max_length=100, null=True)),
                ('description3', models.CharField(default='', max_length=105, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
