# Generated by Django 4.0.6 on 2023-01-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0004_aerosalmodels_breadmodels_soaplmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oilmodel',
            old_name='OilPhoto',
            new_name='oilPhoto',
        ),
    ]
